from homeassistant.components.sensor.const import SensorDeviceClass, SensorStateClass
from homeassistant.const import UnitOfElectricPotential, UnitOfElectricCurrent, UnitOfPower, UnitOfTime, UnitOfEnergy, \
    UnitOfReactivePower, UnitOfFrequency, UnitOfTemperature, UnitOfApparentPower, PERCENTAGE

hybrid_waveshare = [
    {
        "register_start": 33000,
        "scan_interval": 0,
        "entities": [
            {"type": "SS", "name": "Solis Model No", "unique": "solis_modbus_inverter_model_no",
             "register": ['33000'], "multiplier": 0},
            {"type": "SS", "name": "Solis DSP Version", "unique": "solis_modbus_inverter_dsp_version",
             "register": ['33001'], "multiplier": 0},
            {"type": "SS", "name": "Solis HMI Version", "unique": "solis_modbus_inverter_hmi_version",
             "register": ['33002'], "multiplier": 0},
            {"type": "SS", "name": "Solis Protocol Version", "unique": "solis_modbus_inverter_protocol_version",
             "register": ['33003'], "multiplier": 0},
            {"type": "SS", "name": "Solis Serial Number", "unique": "solis_modbus_inverter_serial_number",
             "register": [
                 '33004', '33005', '33006', '33007', '33008', '33009', '33010', '33011', '33012', '33013', '33014',
                 '33015', '33016', '33017', '33018', '33019',
             ], "multiplier": 0}
        ]
    },
    {
        "register_start": 33025,
        "scan_interval": 60,
        "entities": [

            {"type": "SS", "name": "Solis Clock (Hours)",
             "unique": "solis_modbus_inverter_clock_hours",
             "register": ['33025'], "multiplier": 0,
             "unit_of_measurement": UnitOfTime.HOURS, "state_class": SensorStateClass.MEASUREMENT},
            {"type": "SS", "name": "Solis Clock (Minutes)",
             "unique": "solis_modbus_inverter_clock_minutes",
             "register": ['33026'], "multiplier": 0,
             "unit_of_measurement": UnitOfTime.MINUTES, "state_class": SensorStateClass.MEASUREMENT},
            {"type": "SS", "name": "Solis Clock (Seconds)",
             "unique": "solis_modbus_inverter_clock_seconds",
             "register": ['33027'], "multiplier": 0,
             "unit_of_measurement": UnitOfTime.SECONDS, "state_class": SensorStateClass.MEASUREMENT},

            {"type": "reserve", "register": ['33028']},

            {"type": "SS", "name": "Solis PV Total Energy Generation",
             "unique": "solis_modbus_inverter_pv_total_generation",
             "register": ['33029', '33030'], "device_class": SensorDeviceClass.ENERGY, "multiplier": 0,
             "unit_of_measurement": UnitOfEnergy.KILO_WATT_HOUR, "state_class": SensorStateClass.TOTAL_INCREASING},
            {"type": "SS", "name": "Solis PV Current Month Energy Generation",
             "unique": "solis_modbus_inverter_pv_current_month_generation",
             "register": ['33031', '33032'], "device_class": SensorDeviceClass.ENERGY, "multiplier": 1,
             "unit_of_measurement": UnitOfEnergy.KILO_WATT_HOUR, "state_class": SensorStateClass.TOTAL_INCREASING},
            {"type": "SS", "name": "Solis PV Last Month Energy Generation",
             "unique": "solis_modbus_inverter_pv_last_month_generation",
             "register": ['33033', '33034'], "device_class": SensorDeviceClass.ENERGY, "multiplier": 1,
             "unit_of_measurement": UnitOfEnergy.KILO_WATT_HOUR, "state_class": SensorStateClass.TOTAL_INCREASING},
            {"type": "SS", "name": "Solis PV Today Energy Generation",
             "unique": "solis_modbus_inverter_pv_today_generation",
             "register": ['33035'], "device_class": SensorDeviceClass.ENERGY, "multiplier": 0.1,
             "unit_of_measurement": UnitOfEnergy.KILO_WATT_HOUR, "state_class": SensorStateClass.TOTAL_INCREASING},
            {"type": "SS", "name": "Solis PV Yesterday Energy Generation",
             "unique": "solis_modbus_inverter_pv_yesterday_generation",
             "register": ['33036'], "device_class": SensorDeviceClass.ENERGY, "multiplier": 0.1,
             "unit_of_measurement": UnitOfEnergy.KILO_WATT_HOUR, "state_class": SensorStateClass.TOTAL_INCREASING},
            {"type": "SS", "name": "Solis PV This Year Energy Generation",
             "unique": "solis_modbus_inverter_pv_this_year_generation",
             "register": ['33037', '33038'], "device_class": SensorDeviceClass.ENERGY, "multiplier": 1,
             "unit_of_measurement": UnitOfEnergy.KILO_WATT_HOUR, "state_class": SensorStateClass.TOTAL_INCREASING},
            {"type": "SS", "name": "Solis PV Last Year Energy Generation",
             "unique": "solis_modbus_inverter_pv_last_year_generation",
             "register": ['33039', '33040'], "device_class": SensorDeviceClass.ENERGY, "multiplier": 1,
             "unit_of_measurement": UnitOfEnergy.KILO_WATT_HOUR, "state_class": SensorStateClass.TOTAL_INCREASING},
        ]
    },
    {
        "register_start": 33049,
        "scan_interval": 5,
        "entities": [
            {"type": "SS", "name": "Solis PV Voltage 1",
             "unique": "solis_modbus_inverter_dc_voltage_1",
             "register": ['33049'], "device_class": SensorDeviceClass.VOLTAGE, "multiplier": 0.1,
             "unit_of_measurement": UnitOfElectricPotential.VOLT, "state_class": SensorStateClass.MEASUREMENT},

            {"type": "SS", "name": "Solis PV Current 1",
             "unique": "solis_modbus_inverter_dc_current_1",
             "register": ['33050'], "device_class": SensorDeviceClass.CURRENT, "multiplier": 0.1,
             "unit_of_measurement": UnitOfElectricCurrent.AMPERE, "state_class": SensorStateClass.MEASUREMENT},

            {"type": "SS", "name": "Solis PV Voltage 2 ",
             "unique": "solis_modbus_inverter_dc_voltage_2",
             "register": ['33051'], "device_class": SensorDeviceClass.VOLTAGE, "multiplier": 0.1,
             "unit_of_measurement": UnitOfElectricPotential.VOLT, "state_class": SensorStateClass.MEASUREMENT},

            {"type": "SS", "name": "Solis PV Current 2",
             "unique": "solis_modbus_inverter_dc_current_2",
             "register": ['33052'], "device_class": SensorDeviceClass.CURRENT, "multiplier": 0.1,
             "unit_of_measurement": UnitOfElectricCurrent.AMPERE, "state_class": SensorStateClass.MEASUREMENT},

            {"type": "SS", "name": "Solis PV Voltage 3",
             "unique": "solis_modbus_inverter_dc_voltage_3",
             "register": ['33053'], "device_class": SensorDeviceClass.VOLTAGE, "multiplier": 0.1,
             "unit_of_measurement": UnitOfElectricPotential.VOLT, "state_class": SensorStateClass.MEASUREMENT},

            {"type": "SS", "name": "Solis PV Current 3",
             "unique": "solis_modbus_inverter_dc_current_3",
             "register": ['33054'], "device_class": SensorDeviceClass.CURRENT, "multiplier": 0.1,
             "unit_of_measurement": UnitOfElectricCurrent.AMPERE, "state_class": SensorStateClass.MEASUREMENT},

            {"type": "SS", "name": "Solis PV Voltage 4",
             "unique": "solis_modbus_inverter_dc_voltage_4",
             "register": ['33055'], "device_class": SensorDeviceClass.VOLTAGE, "multiplier": 0.1,
             "unit_of_measurement": UnitOfElectricPotential.VOLT, "state_class": SensorStateClass.MEASUREMENT},

            {"type": "SS", "name": "Solis PV Current 4",
             "unique": "solis_modbus_inverter_dc_current_4",
             "register": ['33056'], "device_class": SensorDeviceClass.CURRENT, "multiplier": 0.1,
             "unit_of_measurement": UnitOfElectricCurrent.AMPERE, "state_class": SensorStateClass.MEASUREMENT},

            {"type": "SS", "name": "Solis Total PV Power",
             "unique": "solis_modbus_inverter_total_dc_output",
             "register": ['33057', '33058'], "device_class": SensorDeviceClass.POWER, "multiplier": 0,
             "unit_of_measurement": UnitOfPower.WATT, "state_class": SensorStateClass.MEASUREMENT},
        ]
    },
    {
        "register_start": 33072,
        "scan_interval": 5,
        "entities": [
            {"type": "SS", "name": "Solis PV Bus Half Voltage",
             "unique": "solis_modbus_inverter_dc_bus_half_voltage",
             "register": ['33072'], "device_class": SensorDeviceClass.VOLTAGE, "multiplier": 0.1,
             "unit_of_measurement": UnitOfElectricPotential.VOLT, "state_class": SensorStateClass.MEASUREMENT},

            {"type": "SS", "name": "Solis A Phase Voltage",
             "unique": "solis_modbus_inverter_a_phase_voltage",
             "register": ['33073'], "device_class": SensorDeviceClass.VOLTAGE, "multiplier": 0.1,
             "unit_of_measurement": UnitOfElectricPotential.VOLT, "state_class": SensorStateClass.MEASUREMENT},
            {"type": "SS", "name": "Solis B Phase Voltage",
             "unique": "solis_modbus_inverter_b_phase_voltage",
             "register": ['33074'], "device_class": SensorDeviceClass.VOLTAGE, "multiplier": 0.1,
             "unit_of_measurement": UnitOfElectricPotential.VOLT, "state_class": SensorStateClass.MEASUREMENT},
            {"type": "SS", "name": "Solis C Phase Voltage",
             "unique": "solis_modbus_inverter_c_phase_voltage",
             "register": ['33075'], "device_class": SensorDeviceClass.VOLTAGE, "multiplier": 0.1,
             "unit_of_measurement": UnitOfElectricPotential.VOLT, "state_class": SensorStateClass.MEASUREMENT},

            {"type": "SS", "name": "Solis A Phase Current",
             "unique": "solis_modbus_inverter_a_phase_current",
             "register": ['33076'], "device_class": SensorDeviceClass.CURRENT, "multiplier": 0.1,
             "unit_of_measurement": UnitOfElectricCurrent.AMPERE, "state_class": SensorStateClass.MEASUREMENT},
            {"type": "SS", "name": "Solis B Phase Current",
             "unique": "solis_modbus_inverter_b_phase_current",
             "register": ['33077'], "device_class": SensorDeviceClass.CURRENT, "multiplier": 0.1,
             "unit_of_measurement": UnitOfElectricCurrent.AMPERE, "state_class": SensorStateClass.MEASUREMENT},
            {"type": "SS", "name": "Solis C Phase Current",
             "unique": "solis_modbus_inverter_c_phase_current",
             "register": ['33078'], "device_class": SensorDeviceClass.CURRENT, "multiplier": 0.1,
             "unit_of_measurement": UnitOfElectricCurrent.AMPERE, "state_class": SensorStateClass.MEASUREMENT},

            {"type": "SS", "name": "Solis Active Power",
             "unique": "solis_modbus_inverter_active_power",
             "register": ['33079', '33080'], "device_class": SensorDeviceClass.POWER, "multiplier": 1,
             "unit_of_measurement": UnitOfPower.WATT, "state_class": SensorStateClass.MEASUREMENT},

            {"type": "SS", "name": "Solis Reactive Power",
             "unique": "solis_modbus_inverter_reactive_power",
             "register": ['33081', '33082'], "device_class": SensorDeviceClass.REACTIVE_POWER, "multiplier": 0,
             "unit_of_measurement": UnitOfReactivePower.VOLT_AMPERE_REACTIVE,
             "state_class": SensorStateClass.MEASUREMENT},

            {"type": "SS", "name": "Solis Apparent Power",
             "unique": "solis_modbus_inverter_apparent_power",
             "register": ['33083', '33084'], "device_class": SensorDeviceClass.APPARENT_POWER, "multiplier": 0,
             "unit_of_measurement": UnitOfApparentPower.VOLT_AMPERE, "state_class": SensorStateClass.MEASUREMENT}
        ]
    },
    {
        "register_start": 33093,
        "scan_interval": 5,
        "entities": [
            {"type": "SS", "name": "Solis Temperature", "unique": "solis_modbus_inverter_temperature",
             "register": ['33093'], "device_class": SensorDeviceClass.TEMPERATURE, "multiplier": 0.1,
             "unit_of_measurement": UnitOfTemperature.CELSIUS, "state_class": SensorStateClass.MEASUREMENT},

            {"type": "SS", "name": "Solis Grid Frequency", "unique": "solis_modbus_inverter_grid_frequency",
             "register": ['33094'], "device_class": SensorDeviceClass.FREQUENCY, "multiplier": 0.01,
             "unit_of_measurement": UnitOfFrequency.HERTZ, "state_class": SensorStateClass.MEASUREMENT},

            {"type": "SS", "name": "Solis Status", "unique": "solis_modbus_inverter_current_status",
             "register": ['33095'], "multiplier": 0, "state_class": SensorStateClass.MEASUREMENT},

            {"type": "SS", "name": "Solis Lead-acid Battery Temperature",
             "unique": "solis_modbus_inverter_lead_acid_temp",
             "register": ['33096'], "device_class": SensorDeviceClass.TEMPERATURE, "multiplier": 0.1,
             "unit_of_measurement": UnitOfTemperature.CELSIUS, "state_class": SensorStateClass.MEASUREMENT},
        ]
    },
    {
        "register_start": 33132,
        "scan_interval": 5,
        "entities": [
            {"type": "SS", "name": "Solis Storage Control Switching Value",
             "unique": "solis_modbus_inverter_storage_control_switching_value", "register": ['33132'],
             "multiplier": 0, "state_class": SensorStateClass.MEASUREMENT},
            {"type": "SS", "name": "Solis Battery Voltage",
             "unique": "solis_modbus_inverter_battery_voltage", "register": ['33133'],
             "device_class": SensorDeviceClass.VOLTAGE,
             "multiplier": 0.1, "unit_of_measurement": UnitOfElectricPotential.VOLT,
             "state_class": SensorStateClass.MEASUREMENT},
            {"type": "SS", "name": "Solis Battery Current",
             "unique": "solis_modbus_inverter_battery_current", "register": ['33134'],
             "device_class": SensorDeviceClass.CURRENT,
             "multiplier": 0.1, "unit_of_measurement": UnitOfElectricCurrent.AMPERE,
             "state_class": SensorStateClass.MEASUREMENT},
            {"type": "SS", "name": "Solis Battery Current Direction",
             "unique": "solis_modbus_inverter_battery_current_direction",
             "register": ['33135'],
             "multiplier": 0,
             "state_class": SensorStateClass.MEASUREMENT},
            {"type": "SS", "name": "Solis LLC Bus Voltage",
             "unique": "solis_modbus_inverter_llc_bus_voltage",
             "register": ['33136'], "device_class": SensorDeviceClass.VOLTAGE,
             "multiplier": 0.1,
             "unit_of_measurement": UnitOfElectricPotential.VOLT,
             "state_class": SensorStateClass.MEASUREMENT},
            {"type": "SS", "name": "Solis Backup AC Voltage Phase A",
             "unique": "solis_modbus_inverter_backup_ac_voltage_phase_a",
             "register": ['33137'], "device_class": SensorDeviceClass.VOLTAGE,
             "multiplier": 0.1,
             "unit_of_measurement": UnitOfElectricPotential.VOLT,
             "state_class": SensorStateClass.MEASUREMENT},
            {"type": "SS", "name": "Solis Backup AC Current Phase A",
             "unique": "solis_modbus_inverter_backup_ac_current_phase_a",
             "register": ['33138'], "device_class": SensorDeviceClass.CURRENT,
             "multiplier": 0.1,
             "unit_of_measurement": UnitOfElectricCurrent.AMPERE,
             "state_class": SensorStateClass.MEASUREMENT},

            {"type": "SS", "name": "Solis Battery SOC",
             "unique": "solis_modbus_inverter_battery_soc",
             "register": ['33139'], "device_class": SensorDeviceClass.BATTERY,
             "multiplier": 0,
             "unit_of_measurement": PERCENTAGE,
             "state_class": SensorStateClass.MEASUREMENT},
            {"type": "SS", "name": "Solis Battery SOH",
             "unique": "solis_modbus_inverter_battery_soh", "register": ['33140'], "multiplier": 0,
             "unit_of_measurement": PERCENTAGE, "state_class": SensorStateClass.MEASUREMENT},
            {"type": "SS", "name": "Solis Battery Voltage (BMS)",
             "unique": "solis_modbus_inverter_battery_voltage_bms",
             "register": ['33141'], "device_class": SensorDeviceClass.VOLTAGE, "multiplier": 0.01,
             "unit_of_measurement": UnitOfElectricPotential.VOLT, "state_class": SensorStateClass.MEASUREMENT},
            {"type": "SS", "name": "Solis Battery Current (BMS)",
             "unique": "solis_modbus_inverter_battery_current_bms",
             "register": ['33142'], "device_class": SensorDeviceClass.CURRENT, "multiplier": 0.01,
             "unit_of_measurement": UnitOfElectricCurrent.AMPERE, "state_class": SensorStateClass.MEASUREMENT},
            {"type": "SS", "name": "Solis Battery Charge Current Limitation (BMS)",
             "unique": "solis_modbus_inverter_battery_charge_current_limitation_bms",
             "register": ['33143'], "device_class": SensorDeviceClass.CURRENT, "multiplier": 0.1,
             "unit_of_measurement": UnitOfElectricCurrent.AMPERE, "state_class": SensorStateClass.MEASUREMENT},
            {"type": "SS", "name": "Solis Battery Discharge Current Limitation (BMS)",
             "unique": "solis_modbus_inverter_battery_discharge_current_limitation_bms",
             "register": ['33144'], "device_class": SensorDeviceClass.CURRENT, "multiplier": 0.1,
             "unit_of_measurement": UnitOfElectricCurrent.AMPERE, "state_class": SensorStateClass.MEASUREMENT},
            {"type": "SS", "name": "Solis Battery Fault Status 1 (BMS)",
             "unique": "solis_modbus_inverter_battery_fault_status_1_bms", "register": ['33145'], "multiplier": 0.1,
             "state_class": SensorStateClass.MEASUREMENT},
            {"type": "SS", "name": "Solis Battery Fault Status 2 (BMS)",
             "unique": "solis_modbus_inverter_battery_fault_status_2_bms", "register": ['33146'], "multiplier": 0.1,
             "state_class": SensorStateClass.MEASUREMENT},
            {"type": "SS", "name": "Solis Household load power",
             "unique": "solis_modbus_inverter_household_load_power",
             "register": ['33147'], "device_class": SensorDeviceClass.POWER, "multiplier": 0,
             "unit_of_measurement": UnitOfPower.WATT, "state_class": SensorStateClass.MEASUREMENT},
            {"type": "SS", "name": "Solis Backup Load power",
             "unique": "solis_modbus_inverter_backup_load_power",
             "register": ['33148'], "device_class": SensorDeviceClass.POWER, "multiplier": 0,
             "unit_of_measurement": UnitOfPower.WATT, "state_class": SensorStateClass.MEASUREMENT},
            {"type": "SS", "name": "Solis Battery Power",
             "unique": "solis_modbus_inverter_battery_power",
             "register": ['33149', '33150'], "device_class": SensorDeviceClass.POWER, "multiplier": 0,
             "unit_of_measurement": UnitOfPower.WATT, "state_class": SensorStateClass.MEASUREMENT},
            {"type": "SS", "name": "Solis AC Grid Port Power",
             "unique": "solis_modbus_inverter_ac_grid_port_power",
             "register": ['33151', '33152'], "device_class": SensorDeviceClass.POWER, "multiplier": 0,
             "unit_of_measurement": UnitOfPower.WATT, "state_class": SensorStateClass.MEASUREMENT},
        ]
    },
    {
        "register_start": 33161,
        "scan_interval": 5,
        "entities": [
            {"type": "SS", "name": "Solis Total Battery Charge Energy",
             "unique": "solis_modbus_inverter_total_battery_charge_energy",
             "register": ['33161', '33162'], "device_class": SensorDeviceClass.ENERGY, "multiplier": 0.01,
             "unit_of_measurement": UnitOfEnergy.KILO_WATT_HOUR, "state_class": SensorStateClass.TOTAL_INCREASING},

            {"type": "SS", "name": "Solis Today Battery Charge Energy",
             "unique": "solis_modbus_inverter_today_battery_charge_energy",
             "register": ['33163'], "device_class": SensorDeviceClass.ENERGY, "multiplier": 0.01,
             "unit_of_measurement": UnitOfEnergy.KILO_WATT_HOUR, "state_class": SensorStateClass.TOTAL_INCREASING},
            {"type": "SS", "name": "Solis Yesterday Battery Charge Energy",
             "unique": "solis_modbus_inverter_yesterday_battery_charge_energy",
             "register": ['33164'], "device_class": SensorDeviceClass.ENERGY, "multiplier": 0.01,
             "unit_of_measurement": UnitOfEnergy.KILO_WATT_HOUR, "state_class": SensorStateClass.TOTAL_INCREASING},
            {"type": "SS", "name": "Solis Total Battery Discharge Energy",
             "unique": "solis_modbus_inverter_total_battery_discharge_energy",
             "register": ['33165', '33166'], "device_class": SensorDeviceClass.ENERGY, "multiplier": 0.01,
             "unit_of_measurement": UnitOfEnergy.KILO_WATT_HOUR, "state_class": SensorStateClass.TOTAL_INCREASING},

            {"type": "SS", "name": "Solis Today Battery Discharge Energy",
             "unique": "solis_modbus_inverter_today_battery_discharge_energy",
             "register": ['33167'], "device_class": SensorDeviceClass.ENERGY, "multiplier": 0.01,
             "unit_of_measurement": UnitOfEnergy.KILO_WATT_HOUR, "state_class": SensorStateClass.TOTAL_INCREASING},
            {"type": "SS", "name": "Solis Yesterday Battery Discharge Energy",
             "unique": "solis_modbus_inverter_yesterday_battery_discharge_energy",
             "register": ['33168'], "device_class": SensorDeviceClass.ENERGY, "multiplier": 0.01,
             "unit_of_measurement": UnitOfEnergy.KILO_WATT_HOUR, "state_class": SensorStateClass.TOTAL_INCREASING},

            {"type": "SS", "name": "Solis Total Energy Imported From Grid",
             "unique": "solis_modbus_inverter_total_energy_imported_from_grid",
             "register": ['33169', '33170'], "device_class": SensorDeviceClass.ENERGY, "multiplier": 0,
             "unit_of_measurement": UnitOfEnergy.KILO_WATT_HOUR, "state_class": SensorStateClass.TOTAL_INCREASING},
            {"type": "SS", "name": "Solis Today Energy Imported From Grid",
             "unique": "solis_modbus_inverter_today_energy_imported_from_grid",
             "register": ['33171'], "device_class": SensorDeviceClass.ENERGY, "multiplier": 0.1,
             "unit_of_measurement": UnitOfEnergy.KILO_WATT_HOUR, "state_class": SensorStateClass.TOTAL_INCREASING},
            {"type": "SS", "name": "Solis Yesterday Energy Imported From Grid",
             "unique": "solis_modbus_inverter_yesterday_energy_imported_from_grid",
             "register": ['33172'], "device_class": SensorDeviceClass.ENERGY, "multiplier": 0.1,
             "unit_of_measurement": UnitOfEnergy.KILO_WATT_HOUR, "state_class": SensorStateClass.TOTAL_INCREASING},

            {"type": "SS", "name": "Solis Total Energy Fed Into Grid",
             "unique": "solis_modbus_inverter_total_energy_fed_into_grid",
             "register": ['33173', '33174'], "device_class": SensorDeviceClass.ENERGY, "multiplier": 0,
             "unit_of_measurement": UnitOfEnergy.KILO_WATT_HOUR, "state_class": SensorStateClass.TOTAL_INCREASING},
            {"type": "SS", "name": "Solis Today Energy Fed Into Grid",
             "unique": "solis_modbus_inverter_today_energy_fed_into_grid",
             "register": ['33175'], "device_class": SensorDeviceClass.ENERGY, "multiplier": 0.1,
             "unit_of_measurement": UnitOfEnergy.KILO_WATT_HOUR, "state_class": SensorStateClass.TOTAL_INCREASING},
            {"type": "SS", "name": "Solis Yesterday Energy Fed Into Grid",
             "unique": "solis_modbus_inverter_yesterday_energy_fed_into_grid",
             "register": ['33176'], "device_class": SensorDeviceClass.ENERGY, "multiplier": 0.1,
             "unit_of_measurement": UnitOfEnergy.KILO_WATT_HOUR, "state_class": SensorStateClass.TOTAL_INCREASING},

            {"type": "SS", "name": "Solis Total Energy Consumption",
             "unique": "solis_modbus_inverter_total_energy_consumption",
             "register": ['33177', '33178'], "device_class": SensorDeviceClass.ENERGY, "multiplier": 0,
             "unit_of_measurement": UnitOfEnergy.KILO_WATT_HOUR, "state_class": SensorStateClass.TOTAL_INCREASING},
            {"type": "SS", "name": "Solis Today Energy Consumption",
             "unique": "solis_modbus_inverter_today_energy_consumption",
             "register": ['33179'], "device_class": SensorDeviceClass.ENERGY, "multiplier": 0.1,
             "unit_of_measurement": UnitOfEnergy.KILO_WATT_HOUR, "state_class": SensorStateClass.TOTAL_INCREASING},
            {"type": "SS", "name": "Solis Yesterday Energy Consumption",
             "unique": "solis_modbus_inverter_yesterday_energy_consumption",
             "register": ['33180'], "device_class": SensorDeviceClass.ENERGY, "multiplier": 0.1,
             "unit_of_measurement": UnitOfEnergy.KILO_WATT_HOUR, "state_class": SensorStateClass.TOTAL_INCREASING},
        ]
    },
    {
        "register_start": 33251,
        "scan_interval": 5,
        "entities": [
            {"type": "SS", "name": "Solis Meter AC Voltage A",
             "unique": "solis_modbus_inverter_meter_ac_voltage_a",
             "register": ['33251'], "device_class": SensorDeviceClass.VOLTAGE, "multiplier": 0.1,
             "unit_of_measurement": UnitOfElectricPotential.VOLT, "state_class": SensorStateClass.MEASUREMENT},
            {"type": "SS", "name": "Solis Meter AC Current A",
             "unique": "solis_modbus_inverter_meter_ac_current_a",
             "register": ['33252'], "device_class": SensorDeviceClass.CURRENT, "multiplier": 0.01,
             "unit_of_measurement": UnitOfElectricCurrent.AMPERE, "state_class": SensorStateClass.MEASUREMENT},
            {"type": "SS", "name": "Solis Meter AC Voltage B",
             "unique": "solis_modbus_inverter_meter_ac_voltage_b",
             "register": ['33253'], "device_class": SensorDeviceClass.VOLTAGE, "multiplier": 0.1,
             "unit_of_measurement": UnitOfElectricPotential.VOLT, "state_class": SensorStateClass.MEASUREMENT},
            {"type": "SS", "name": "Solis Meter AC Current B",
             "unique": "solis_modbus_inverter_meter_ac_current_b",
             "register": ['33254'], "device_class": SensorDeviceClass.CURRENT, "multiplier": 0.01,
             "unit_of_measurement": UnitOfElectricCurrent.AMPERE, "state_class": SensorStateClass.MEASUREMENT},
            {"type": "SS", "name": "Solis Meter AC Voltage C",
             "unique": "solis_modbus_inverter_meter_ac_voltage_c",
             "register": ['33255'], "device_class": SensorDeviceClass.VOLTAGE, "multiplier": 0.1,
             "unit_of_measurement": UnitOfElectricPotential.VOLT, "state_class": SensorStateClass.MEASUREMENT},
            {"type": "SS", "name": "Solis Meter AC Current C",
             "unique": "solis_modbus_inverter_meter_ac_current_c",
             "register": ['33256'], "device_class": SensorDeviceClass.CURRENT, "multiplier": 0.01,
             "unit_of_measurement": UnitOfElectricCurrent.AMPERE, "state_class": SensorStateClass.MEASUREMENT},

            {"type": "SS", "name": "Solis Meter Active Power A",
             "unique": "solis_modbus_inverter_meter_active_power_a",
             "register": ['33257', '33258'], "device_class": SensorDeviceClass.POWER, "multiplier": 0,
             "unit_of_measurement": UnitOfPower.WATT, "state_class": SensorStateClass.MEASUREMENT},
            {"type": "SS", "name": "Solis Meter Active Power B",
             "unique": "solis_modbus_inverter_meter_active_power_b",
             "register": ['33259', '33260'], "device_class": SensorDeviceClass.POWER, "multiplier": 0,
             "unit_of_measurement": UnitOfPower.WATT, "state_class": SensorStateClass.MEASUREMENT},
            {"type": "SS", "name": "Solis Meter Active Power C",
             "unique": "solis_modbus_inverter_meter_active_power_c",
             "register": ['33261', '33262'], "device_class": SensorDeviceClass.POWER, "multiplier": 0,
             "unit_of_measurement": UnitOfPower.WATT, "state_class": SensorStateClass.MEASUREMENT},
            {"type": "SS", "name": "Solis Meter Total Active Power",
             "unique": "solis_modbus_inverter_meter_total_active_power",
             "register": ['33263', '33264'], "device_class": SensorDeviceClass.POWER, "multiplier": 0,
             "unit_of_measurement": UnitOfPower.WATT, "state_class": SensorStateClass.MEASUREMENT}
        ]
    },
    {
        "register_start": 33580,
        "scan_interval": 60,
        "entities": [
            {"type": "SS", "name": "Solis Household Load Total Energy",
             "unique": "solis_modbus_inverter_household_total_energy",
             "register": ['33580', '33581'], "device_class": SensorDeviceClass.ENERGY, "multiplier": 0,
             "unit_of_measurement": UnitOfEnergy.KILO_WATT_HOUR, "state_class": SensorStateClass.TOTAL_INCREASING},
            {"type": "SS", "name": "Solis Household Load Year Energy",
             "unique": "solis_modbus_inverter_household_year_energy",
             "register": ['33582', '33583'], "device_class": SensorDeviceClass.ENERGY, "multiplier": 0,
             "unit_of_measurement": UnitOfEnergy.KILO_WATT_HOUR, "state_class": SensorStateClass.TOTAL_INCREASING},
            {"type": "SS", "name": "Solis Household Load Month Energy",
             "unique": "solis_modbus_inverter_household_month_energy",
             "register": ['33584', '33585'], "device_class": SensorDeviceClass.ENERGY, "multiplier": 1,
             "unit_of_measurement": UnitOfEnergy.KILO_WATT_HOUR, "state_class": SensorStateClass.TOTAL_INCREASING},
            {"type": "SS", "name": "Solis Household Load Today Energy",
             "unique": "solis_modbus_inverter_household_today_energy",
             "register": ['33586'], "device_class": SensorDeviceClass.ENERGY, "multiplier": 0.1,
             "unit_of_measurement": UnitOfEnergy.KILO_WATT_HOUR, "state_class": SensorStateClass.TOTAL_INCREASING},
            {"type": "reserve", "register": ['33587', '33588', '33589']},

            {"type": "SS", "name": "Solis Backup Load Total Energy",
             "unique": "solis_modbus_inverter_backup_total_energy",
             "register": ['33590', '33591'], "device_class": SensorDeviceClass.ENERGY, "multiplier": 0,
             "unit_of_measurement": UnitOfEnergy.KILO_WATT_HOUR, "state_class": SensorStateClass.TOTAL_INCREASING},
            {"type": "SS", "name": "Solis Backup Load Year Energy",
             "unique": "solis_modbus_inverter_backup_year_energy",
             "register": ['33592', '33593'], "device_class": SensorDeviceClass.ENERGY, "multiplier": 0,
             "unit_of_measurement": UnitOfEnergy.KILO_WATT_HOUR, "state_class": SensorStateClass.TOTAL_INCREASING},
            {"type": "SS", "name": "Solis Backup Load Month Energy",
             "unique": "solis_modbus_inverter_backup_month_energy",
             "register": ['33594', '33595'], "device_class": SensorDeviceClass.ENERGY, "multiplier": 1,
             "unit_of_measurement": UnitOfEnergy.KILO_WATT_HOUR, "state_class": SensorStateClass.TOTAL_INCREASING},
            {"type": "SS", "name": "Solis Backup Load Today Energy",
             "unique": "solis_modbus_inverter_backup_today_energy",
             "register": ['33596'], "device_class": SensorDeviceClass.ENERGY, "multiplier": 0.1,
             "unit_of_measurement": UnitOfEnergy.KILO_WATT_HOUR, "state_class": SensorStateClass.TOTAL_INCREASING},
        ]
    },
    {
        "register_start": 43011,
        "scan_interval": 10,
        "entities": [

            {"type": "SS", "name": "Solis Overcharge SOC",
             "unique": "solis_modbus_inverter_overcharge_soc", "register": ['43010'], "multiplier": 0,
             "unit_of_measurement": PERCENTAGE, "state_class": SensorStateClass.MEASUREMENT, "editable": True,
             "default": 90,
             "min": 70, "max": 100, "step": 1},

            {"type": "SS", "name": "Solis Overdischarge SOC",
             "unique": "solis_modbus_inverter_overdischarge_soc", "register": ['43011'], "multiplier": 0,
             "unit_of_measurement": PERCENTAGE, "state_class": SensorStateClass.MEASUREMENT, "editable": True,
             "default": 20, "min": 5, "max": 40, "step": 1, },

            {"type": "reserve", "register": ['43012', '43013', '43014', '43015', '43016', '43017']},

            {"type": "SS", "name": "Solis Force Charge SOC",
             "unique": "solis_modbus_inverter_force_charge_soc", "register": ['43018'], "multiplier": 0,
             "unit_of_measurement": PERCENTAGE, "state_class": SensorStateClass.MEASUREMENT, "editable": True,
             "default": 10,
             "min": 0, "max": 100, "step": 1, },

            {"type": "reserve", "register": ['43019', '43020', '43021', '43022', '43023']},

            {"type": "SS", "name": "Solis Backup SOC",
             "unique": "solis_modbus_inverter_backup_soc", "register": ['43024'], "multiplier": 0,
             "unit_of_measurement": PERCENTAGE, "state_class": SensorStateClass.MEASUREMENT, "editable": True,
             "default": 80.0,
             "min": 0, "max": 100, "step": 1, },
            {"type": "reserve", "register": ['43025', '43026']},
            {"type": "SS", "name": "Solis Battery Force-charge Power Limitation",
             "unique": "solis_modbus_inverter_battery_force_charge_limit",
             "register": ['43027'], "device_class": SensorDeviceClass.POWER, "multiplier": 10,
             "unit_of_measurement": UnitOfPower.WATT, "state_class": SensorStateClass.MEASUREMENT, "editable": True,
             "default": 3000.0,
             "min": 0, "max": 6000},
            {"type": "SS", "name": "Solis Battery Force Charge Source",
             "unique": "solis_modbus_inverter_battery_force_charge_source", "register": ['43028'], "multiplier": 0,
             "state_class": SensorStateClass.MEASUREMENT}
        ]
    },
    {
        "register_start": 43135,
        "entities": [
            {"type": "SS", "name": "Solis RC Force Battery Charge/discharge",
             "unique": "solis_modbus_inverter_rc_force_charge_discharge", "hidden": True,
             "register": ['43135'], "multiplier": 1, "state_class": SensorStateClass.MEASUREMENT},
            {"type": "SS", "name": "Solis RC Force Battery Charge Power",
             "unique": "solis_modbus_inverter_rc_force_charge_power",
             "unit_of_measurement": UnitOfPower.KILO_WATT, "device_class": SensorDeviceClass.POWER,
             "state_class": SensorStateClass.MEASUREMENT, "editable": True, "min": 0, "max": 6000, "default": 1500,
             "register": ['43136'], "multiplier": 10},
            {"type": "SS", "name": "Solis Off-Grid Overdischarge SOC",
             "unique": "solis_modbus_inverter_overdischarge_offgrid_soc",
             "register": ['43137'], "device_class": SensorDeviceClass.CURRENT, "multiplier": 1,
             "unit_of_measurement": PERCENTAGE, "state_class": SensorStateClass.MEASUREMENT,
             "editable": True, "min": 10, "max": 100, "default": 10},
        ]
    },
    {
        "register_start": 43141,
        "scan_interval": 10,
        "entities": [
            {"type": "SS", "name": "Solis Time-Charging Charge Current",
             "unique": "solis_modbus_inverter_time_charging_charge_current",
             "register": ['43141'], "device_class": SensorDeviceClass.CURRENT, "multiplier": 0.1,
             "unit_of_measurement": UnitOfElectricCurrent.AMPERE, "state_class": SensorStateClass.MEASUREMENT,
             "editable": True, "min": 0, "max": 135, "step": 0.1, "default": 50},
            {"type": "SS", "name": "Solis Time-Charging Discharge Current",
             "unique": "solis_modbus_inverter_time_charging_discharge_current",
             "register": ['43142'], "device_class": SensorDeviceClass.CURRENT, "multiplier": 0.1,
             "unit_of_measurement": UnitOfElectricCurrent.AMPERE, "state_class": SensorStateClass.MEASUREMENT,
             "editable": True, "min": 0, "max": 135, "step": 0.1, "default": 50},

            {"type": "SS", "name": "Solis Time-Charging Charge Start Hour (Slot 1)",
             "unique": "solis_modbus_inverter_time_charging_start_hour_slot1",
             "register": ['43143'], "multiplier": 0, "unit_of_measurement": UnitOfTime.HOURS,
             "state_class": SensorStateClass.MEASUREMENT},
            {"type": "SS", "name": "Solis Time-Charging Charge Start Minute (Slot 1)",
             "unique": "solis_modbus_inverter_time_charging_start_minute_slot1",
             "register": ['43144'], "multiplier": 0, "unit_of_measurement": UnitOfTime.MINUTES,
             "state_class": SensorStateClass.MEASUREMENT},
            {"type": "SS", "name": "Solis Time-Charging Charge End Hour (Slot 1)",
             "unique": "solis_modbus_inverter_time_charging_end_hour_slot1",
             "register": ['43145'], "multiplier": 0,
             "unit_of_measurement": UnitOfTime.HOURS, "state_class": SensorStateClass.MEASUREMENT},
            {"type": "SS", "name": "Solis Time-Charging Charge End Minute (Slot 1)",
             "unique": "solis_modbus_inverter_time_charging_end_minute_slot1",
             "register": ['43146'], "multiplier": 0,
             "unit_of_measurement": UnitOfTime.MINUTES, "state_class": SensorStateClass.MEASUREMENT},

            {"type": "SS", "name": "Solis Time-Charging Discharge Start Hour (Slot 1)",
             "unique": "solis_modbus_inverter_time_discharge_start_hour_slot1", "register": ['43147'],
             "multiplier": 0, "unit_of_measurement": UnitOfTime.HOURS, "state_class": SensorStateClass.MEASUREMENT},
            {"type": "SS", "name": "Solis Time-Charging Discharge Start Minute (Slot 1)",
             "unique": "solis_modbus_inverter_time_discharge_start_minute_slot1", "register": ['43148'],
             "multiplier": 0,
             "unit_of_measurement": UnitOfTime.MINUTES, "state_class": SensorStateClass.MEASUREMENT},
            {"type": "SS", "name": "Solis Time-Charging Discharge End Hour (Slot 1)",
             "unique": "solis_modbus_inverter_time_discharge_end_hour_slot1", "register": ['43149'],
             "multiplier": 0, "unit_of_measurement": UnitOfTime.HOURS, "state_class": SensorStateClass.MEASUREMENT},
            {"type": "SS", "name": "Solis Time-Charging Discharge End Minute (Slot 1)",
             "unique": "solis_modbus_inverter_time_discharge_end_minute_slot1", "register": ['43150'],
             "multiplier": 0, "unit_of_measurement": UnitOfTime.MINUTES,
             "state_class": SensorStateClass.MEASUREMENT},

            {"type": "reserve", "register": ['43051', '43052']},

            {"type": "SS", "name": "Solis Time-Charging Charge Start Hour (Slot 2)",
             "unique": "solis_modbus_inverter_time_charging_start_hour_slot2", "register": ['43153'],
             "multiplier": 0, "unit_of_measurement": UnitOfTime.HOURS, "state_class": SensorStateClass.MEASUREMENT},
            {"type": "SS", "name": "Solis Time-Charging Charge Start Minute (Slot 2)",
             "unique": "solis_modbus_inverter_time_charging_start_minute_slot2", "register": ['43154'],
             "multiplier": 0, "unit_of_measurement": UnitOfTime.MINUTES,
             "state_class": SensorStateClass.MEASUREMENT},
            {"type": "SS", "name": "Solis Time-Charging Charge End Hour (Slot 2)",
             "unique": "solis_modbus_inverter_time_charging_end_hour_slot2", "register": ['43155'], "multiplier": 0,
             "unit_of_measurement": UnitOfTime.HOURS, "state_class": SensorStateClass.MEASUREMENT},
            {"type": "SS", "name": "Solis Time-Charging Charge End Minute (Slot 2)",
             "unique": "solis_modbus_inverter_time_charging_end_minute_slot2",
             "register": ['43156'], "multiplier": 0,
             "unit_of_measurement": UnitOfTime.MINUTES, "state_class": SensorStateClass.MEASUREMENT},

            {"type": "SS", "name": "Solis Time-Charging Discharge Start Hour (Slot 2)",
             "unique": "solis_modbus_inverter_time_discharge_start_hour_slot2",
             "register": ['43157'], "multiplier": 0,
             "unit_of_measurement": UnitOfTime.HOURS, "state_class": SensorStateClass.MEASUREMENT},
            {"type": "SS", "name": "Solis Time-Charging Discharge Start Minute (Slot 2)",
             "unique": "solis_modbus_inverter_time_discharge_start_minute_slot2",
             "register": ['43158'], "multiplier": 0,
             "unit_of_measurement": UnitOfTime.MINUTES, "state_class": SensorStateClass.MEASUREMENT},
            {"type": "SS", "name": "Solis Time-Charging Discharge End Hour (Slot 2)",
             "unique": "solis_modbus_inverter_time_discharge_end_hour_slot2",
             "register": ['43159'], "multiplier": 0,
             "unit_of_measurement": UnitOfTime.HOURS, "state_class": SensorStateClass.MEASUREMENT},
            {"type": "SS", "name": "Solis Time-Charging Discharge End Minute (Slot 2)",
             "unique": "solis_modbus_inverter_time_discharge_end_minute_slot2",
             "register": ['43160'], "multiplier": 0,
             "unit_of_measurement": UnitOfTime.MINUTES, "state_class": SensorStateClass.MEASUREMENT},

            {"type": "reserve", "register": ['43061', '43062']},

            {"type": "SS", "name": "Solis Time-Charging Charge Start Hour (Slot 3)",
             "unique": "solis_modbus_inverter_time_charging_start_hour_slot3",
             "register": ['43163'], "multiplier": 0,
             "unit_of_measurement": UnitOfTime.HOURS, "state_class": SensorStateClass.MEASUREMENT},
            {"type": "SS", "name": "Solis Time-Charging Charge Start Minute (Slot 3)",
             "unique": "solis_modbus_inverter_time_charging_start_minute_slot3",
             "register": ['43164'], "multiplier": 0,
             "unit_of_measurement": UnitOfTime.MINUTES, "state_class": SensorStateClass.MEASUREMENT},
            {"type": "SS", "name": "Solis Time-Charging Charge End Hour (Slot 3)",
             "unique": "solis_modbus_inverter_time_charging_end_hour_slot3",
             "register": ['43165'], "multiplier": 0,
             "unit_of_measurement": UnitOfTime.HOURS, "state_class": SensorStateClass.MEASUREMENT},
            {"type": "SS", "name": "Solis Time-Charging Charge End Minute (Slot 3)",
             "unique": "solis_modbus_inverter_time_charging_end_minute_slot3",
             "register": ['43166'], "multiplier": 0,
             "unit_of_measurement": UnitOfTime.MINUTES, "state_class": SensorStateClass.MEASUREMENT},

            {"type": "SS", "name": "Solis Time-Charging Discharge Start Hour (Slot 3)",
             "unique": "solis_modbus_inverter_time_discharge_start_hour_slot3",
             "register": ['43167'], "multiplier": 0,
             "unit_of_measurement": UnitOfTime.HOURS, "state_class": SensorStateClass.MEASUREMENT},
            {"type": "SS", "name": "Solis Time-Charging Discharge Start Minute (Slot 3)",
             "unique": "solis_modbus_inverter_time_discharge_start_minute_slot3",
             "register": ['43168'], "multiplier": 0,
             "unit_of_measurement": UnitOfTime.MINUTES, "state_class": SensorStateClass.MEASUREMENT},
            {"type": "SS", "name": "Solis Time-Charging Discharge End Hour (Slot 3)",
             "unique": "solis_modbus_inverter_time_discharge_end_hour_slot3",
             "register": ['43169'], "multiplier": 0,
             "unit_of_measurement": UnitOfTime.HOURS, "state_class": SensorStateClass.MEASUREMENT},
            {"type": "SS", "name": "Solis Time-Charging Discharge End Minute (Slot 3)",
             "unique": "solis_modbus_inverter_time_discharge_end_minute_slot3",
             "register": ['43170'], "multiplier": 0,
             "unit_of_measurement": UnitOfTime.MINUTES, "state_class": SensorStateClass.MEASUREMENT},
        ]
    },
    {
        "register_start": 43173,
        "entities": [

            {"type": "SS", "name": "Solis Time-Charging Charge Start Hour (Slot 4)",
             "unique": "solis_modbus_inverter_time_charging_start_hour_slot4",
             "register": ['43173'], "multiplier": 0,
             "unit_of_measurement": UnitOfTime.HOURS, "state_class": SensorStateClass.MEASUREMENT},
            {"type": "SS", "name": "Solis Time-Charging Charge Start Minute (Slot 4)",
             "unique": "solis_modbus_inverter_time_charging_start_minute_slot4",
             "register": ['43174'], "multiplier": 0,
             "unit_of_measurement": UnitOfTime.MINUTES, "state_class": SensorStateClass.MEASUREMENT},
            {"type": "SS", "name": "Solis Time-Charging Charge End Hour (Slot 4)",
             "unique": "solis_modbus_inverter_time_charging_end_hour_slot4",
             "register": ['43175'], "multiplier": 0,
             "unit_of_measurement": UnitOfTime.HOURS, "state_class": SensorStateClass.MEASUREMENT},
            {"type": "SS", "name": "Solis Time-Charging Charge End Minute (Slot 4)",
             "unique": "solis_modbus_inverter_time_charging_end_minute_slot4",
             "register": ['43176'], "multiplier": 0,
             "unit_of_measurement": UnitOfTime.MINUTES, "state_class": SensorStateClass.MEASUREMENT},

            {"type": "SS", "name": "Solis Time-Charging Discharge Start Hour (Slot 4)",
             "unique": "solis_modbus_inverter_time_discharge_start_hour_slot4",
             "register": ['43177'], "multiplier": 0,
             "unit_of_measurement": UnitOfTime.HOURS, "state_class": SensorStateClass.MEASUREMENT},
            {"type": "SS", "name": "Solis Time-Charging Discharge Start Minute (Slot 4)",
             "unique": "solis_modbus_inverter_time_discharge_start_minute_slot4",
             "register": ['43178'], "multiplier": 0,
             "unit_of_measurement": UnitOfTime.MINUTES, "state_class": SensorStateClass.MEASUREMENT},
            {"type": "SS", "name": "Solis Time-Charging Discharge End Hour (Slot 4)",
             "unique": "solis_modbus_inverter_time_discharge_end_hour_slot4",
             "register": ['43179'], "multiplier": 0,
             "unit_of_measurement": UnitOfTime.HOURS, "state_class": SensorStateClass.MEASUREMENT},
            {"type": "SS", "name": "Solis Time-Charging Discharge End Minute (Slot 4)",
             "unique": "solis_modbus_inverter_time_discharge_end_minute_slot4",
             "register": ['43180'], "multiplier": 0,
             "unit_of_measurement": UnitOfTime.MINUTES, "state_class": SensorStateClass.MEASUREMENT},

            {"type": "reserve", "register": ['43081', '43082']},

            {"type": "SS", "name": "Solis Time-Charging Charge Start Hour (Slot 5)",
             "unique": "solis_modbus_inverter_time_charging_start_hour_slot5",
             "register": ['43183'], "multiplier": 0,
             "unit_of_measurement": UnitOfTime.HOURS, "state_class": SensorStateClass.MEASUREMENT},
            {"type": "SS", "name": "Solis Time-Charging Charge Start Minute (Slot 5)",
             "unique": "solis_modbus_inverter_time_charging_start_minute_slot5",
             "register": ['43184'], "multiplier": 0,
             "unit_of_measurement": UnitOfTime.MINUTES, "state_class": SensorStateClass.MEASUREMENT},
            {"type": "SS", "name": "Solis Time-Charging Charge End Hour (Slot 5)",
             "unique": "solis_modbus_inverter_time_charging_end_hour_slot5",
             "register": ['43185'], "multiplier": 0,
             "unit_of_measurement": UnitOfTime.HOURS, "state_class": SensorStateClass.MEASUREMENT},
            {"type": "SS", "name": "Solis Time-Charging Charge End Minute (Slot 5)",
             "unique": "solis_modbus_inverter_time_charging_end_minute_slot5",
             "register": ['43186'], "multiplier": 0,
             "unit_of_measurement": UnitOfTime.MINUTES, "state_class": SensorStateClass.MEASUREMENT},

            {"type": "SS", "name": "Solis Time-Charging Discharge Start Hour (Slot 5)",
             "unique": "solis_modbus_inverter_time_discharge_start_hour_slot5",
             "register": ['43187'], "multiplier": 0,
             "unit_of_measurement": UnitOfTime.HOURS, "state_class": SensorStateClass.MEASUREMENT},
            {"type": "SS", "name": "Solis Time-Charging Discharge Start Minute (Slot 5)",
             "unique": "solis_modbus_inverter_time_discharge_start_minute_slot5",
             "register": ['43188'], "multiplier": 0,
             "unit_of_measurement": UnitOfTime.MINUTES, "state_class": SensorStateClass.MEASUREMENT},
            {"type": "SS", "name": "Solis Time-Charging Discharge End Hour (Slot 5)",
             "unique": "solis_modbus_inverter_time_discharge_end_hour_slot5",
             "register": ['43189'], "multiplier": 0,
             "unit_of_measurement": UnitOfTime.HOURS, "state_class": SensorStateClass.MEASUREMENT},
            {"type": "SS", "name": "Solis Time-Charging Discharge End Minute (Slot 5)",
             "unique": "solis_modbus_inverter_time_discharge_end_minute_slot5",
             "register": ['43190'], "multiplier": 0,
             "unit_of_measurement": UnitOfTime.MINUTES, "state_class": SensorStateClass.MEASUREMENT},
        ]
    }, {
        "register_start": 43363,
        "entities": [
            {"type": "SS", "name": "Solis Forced Start of Generator",
             "unique": "solis_modbus_inverter_generator_forced_start", "register": ['43363'], "multiplier": 1,
             "state_class": SensorStateClass.MEASUREMENT, "switch": True},
            {"type": "SS", "name": "Solis Rated Input Power of Generator",
             "unique": "solis_modbus_inverter_generator_rated_input_power", "register": ['43364'], "multiplier": 0.1,
             "device_class": SensorDeviceClass.POWER, "unit_of_measurement": UnitOfPower.KILO_WATT,
             "state_class": SensorStateClass.MEASUREMENT, "editable": True, "min": 0, "max": 100},
            {"type": "SS", "name": "Solis Generator Setting Switch",
             "unique": "solis_modbus_inverter_generator_setting_switch", "register": ['43365'], "multiplier": 1,
             "state_class": SensorStateClass.MEASUREMENT},
            {"type": "SS", "name": "Solis Generator Forced Stop of Generator",
             "unique": "solis_modbus_inverter_generator_forced_stop", "register": ['43366'], "multiplier": 1,
             "state_class": SensorStateClass.MEASUREMENT, "switch": True},
            {"type": "SS", "name": "Solis Maximum Allowable Percentage of Generator",
             "unique": "solis_modbus_inverter_generator_allowed_percentage", "register": ['43367'], "multiplier": 1,
             "unit_of_measurement": PERCENTAGE, "min": 0.01, "max": 100, "default": 100,
             "state_class": SensorStateClass.MEASUREMENT, "editable": True},
            {"type": "SS", "name": "Solis Generator Target Power",
             "unique": "solis_modbus_inverter_generator_target_power", "register": ['43368'], "multiplier": 0.1,
             "unit_of_measurement": UnitOfPower.KILO_WATT, "device_class": SensorDeviceClass.POWER,
             "state_class": SensorStateClass.MEASUREMENT, "editable": True, "min": 0, "max": 100, "default": 90},
            {"type": "SS", "name": "Solis Generator Charging Power",
             "unique": "solis_modbus_inverter_generator_charging_power", "register": ['43369'], "multiplier": 0.1,
             "unit_of_measurement": UnitOfPower.KILO_WATT, "device_class": SensorDeviceClass.POWER,
             "state_class": SensorStateClass.MEASUREMENT, "editable": True, "min": 0, "max": 100},
        ]
    }, {
        "register_start": 43707,
        "entities": [
            {"type": "SS", "name": "Solis Time of Use V2 Switch", "register": ['43707'],
             "unique": "solis_modbus_inverter_tou_v2_switch"},

            {"type": "SS", "name": "Solis Grid Time of Use Charge cut off SOC (Slot 1)", "register": ['43708'],
             "unique": "solis_modbus_inverter_tou_charge_cutoff_charge_1", "multiplier": 1,
             "unit_of_measurement": PERCENTAGE, "state_class": SensorStateClass.MEASUREMENT, "editable": True, "min": 0,
             "max": 100},
            {"type": "SS", "name": "Solis Grid Time of Use Charge battery current (Slot 1)", "register": ['43709'],
             "unique": "solis_modbus_inverter_tou_charge_v2_battery_current_1", "multiplier": 0.1,
             "device_class": SensorDeviceClass.CURRENT, "unit_of_measurement": UnitOfElectricCurrent.AMPERE,
             "state_class": SensorStateClass.MEASUREMENT, "editable": True, "min": 0, "max": 300},
            {"type": "SS", "name": "Solis Grid Time of Use Charge cut off voltage (Slot 1)", "register": ['43710'],
             "unique": "solis_modbus_inverter_tou_charge_v2_cutoff_voltage_1", "multiplier": 0.1,
             "device_class": SensorDeviceClass.VOLTAGE, "unit_of_measurement": UnitOfElectricPotential.VOLT,
             "state_class": SensorStateClass.MEASUREMENT, "editable": True, "min": 0, "max": 300},

            {"type": "SS", "name": "Solis Grid Time of Use Charge Start Hour (Slot 1)", "register": ['43711'],
             "unique": "solis_modbus_inverter_tou_charge_start_hour_1", "multiplier": 0,
             "unit_of_measurement": UnitOfTime.HOURS, "state_class": SensorStateClass.MEASUREMENT},
            {"type": "SS", "name": "Solis Grid Time of Use Charge Start Minute (Slot 1)", "register": ['43712'],
             "unique": "solis_modbus_inverter_tou_charge_start_minute_1", "multiplier": 0,
             "unit_of_measurement": UnitOfTime.MINUTES, "state_class": SensorStateClass.MEASUREMENT},
            {"type": "SS", "name": "Solis Grid Time of Use Charge End Hour (Slot 1)", "register": ['43713'],
             "unique": "solis_modbus_inverter_tou_charge_end_hour_1", "multiplier": 0,
             "unit_of_measurement": UnitOfTime.HOURS, "state_class": SensorStateClass.MEASUREMENT},
            {"type": "SS", "name": "Solis Grid Time of Use Charge End Minute (Slot 1)", "register": ['43714'],
             "unique": "solis_modbus_inverter_tou_charge_end_minute_1", "multiplier": 0,
             "unit_of_measurement": UnitOfTime.MINUTES, "state_class": SensorStateClass.MEASUREMENT},

            {"type": "SS", "name": "Solis Grid Time of Use Charge cut off SOC (Slot 2)", "register": ['43715'],
             "unique": "solis_modbus_inverter_tou_charge_cutoff_charge_2", "multiplier": 1,
             "unit_of_measurement": PERCENTAGE, "state_class": SensorStateClass.MEASUREMENT, "editable": True, "min": 0,
             "max": 100},
            {"type": "SS", "name": "Solis Grid Time of Use Charge battery current (Slot 2)", "register": ['43716'],
             "unique": "solis_modbus_inverter_tou_charge_v2_battery_current_2", "multiplier": 0.1,
             "device_class": SensorDeviceClass.CURRENT, "unit_of_measurement": UnitOfElectricCurrent.AMPERE,
             "state_class": SensorStateClass.MEASUREMENT, "editable": True, "min": 0, "max": 300},
            {"type": "SS", "name": "Solis Grid Time of Use Charge cut off voltage (Slot 2)", "register": ['43717'],
             "unique": "solis_modbus_inverter_tou_charge_v2_cutoff_voltage_2", "multiplier": 0.1,
             "device_class": SensorDeviceClass.VOLTAGE, "unit_of_measurement": UnitOfElectricPotential.VOLT,
             "state_class": SensorStateClass.MEASUREMENT, "editable": True, "min": 0, "max": 300},

            {"type": "SS", "name": "Solis Grid Time of Use Charge Start Hour (Slot 2)", "register": ['43718'],
             "unique": "solis_modbus_inverter_tou_charge_start_hour_2", "multiplier": 0,
             "unit_of_measurement": UnitOfTime.HOURS, "state_class": SensorStateClass.MEASUREMENT},
            {"type": "SS", "name": "Solis Grid Time of Use Charge Start Minute (Slot 2)", "register": ['43719'],
             "unique": "solis_modbus_inverter_tou_charge_start_minute_2", "multiplier": 0,
             "unit_of_measurement": UnitOfTime.MINUTES, "state_class": SensorStateClass.MEASUREMENT},
            {"type": "SS", "name": "Solis Grid Time of Use Charge End Hour (Slot 2)", "register": ['43720'],
             "unique": "solis_modbus_inverter_tou_charge_end_hour_2", "multiplier": 0,
             "unit_of_measurement": UnitOfTime.HOURS, "state_class": SensorStateClass.MEASUREMENT},
            {"type": "SS", "name": "Solis Grid Time of Use Charge End Minute (Slot 2)", "register": ['43721'],
             "unique": "solis_modbus_inverter_tou_charge_end_minute_2", "multiplier": 0,
             "unit_of_measurement": UnitOfTime.MINUTES, "state_class": SensorStateClass.MEASUREMENT},

            {"type": "SS", "name": "Solis Grid Time of Use Charge cut off SOC (Slot 3)", "register": ['43722'],
             "unique": "solis_modbus_inverter_tou_charge_cutoff_charge_3", "multiplier": 1,
             "unit_of_measurement": PERCENTAGE, "state_class": SensorStateClass.MEASUREMENT, "editable": True, "min": 0,
             "max": 100},
            {"type": "SS", "name": "Solis Grid Time of Use Charge battery current (Slot 3)", "register": ['43723'],
             "unique": "solis_modbus_inverter_tou_charge_v2_battery_current_3", "multiplier": 0.1,
             "device_class": SensorDeviceClass.CURRENT, "unit_of_measurement": UnitOfElectricCurrent.AMPERE,
             "state_class": SensorStateClass.MEASUREMENT, "editable": True, "min": 0, "max": 300},
            {"type": "SS", "name": "Solis Grid Time of Use Charge cut off voltage (Slot 3)", "register": ['43724'],
             "unique": "solis_modbus_inverter_tou_charge_v2_cutoff_voltage_3", "multiplier": 0.1,
             "device_class": SensorDeviceClass.VOLTAGE, "unit_of_measurement": UnitOfElectricPotential.VOLT,
             "state_class": SensorStateClass.MEASUREMENT, "editable": True, "min": 0, "max": 300},

            {"type": "SS", "name": "Solis Grid Time of Use Charge Start Hour (Slot 3)", "register": ['43725'],
             "unique": "solis_modbus_inverter_tou_charge_start_hour_3", "multiplier": 0,
             "unit_of_measurement": UnitOfTime.HOURS, "state_class": SensorStateClass.MEASUREMENT},
            {"type": "SS", "name": "Solis Grid Time of Use Charge Start Minute (Slot 3)", "register": ['43726'],
             "unique": "solis_modbus_inverter_tou_charge_start_minute_3", "multiplier": 0,
             "unit_of_measurement": UnitOfTime.MINUTES, "state_class": SensorStateClass.MEASUREMENT},
            {"type": "SS", "name": "Solis Grid Time of Use Charge End Hour (Slot 3)", "register": ['43727'],
             "unique": "solis_modbus_inverter_tou_charge_end_hour_3", "multiplier": 0,
             "unit_of_measurement": UnitOfTime.HOURS, "state_class": SensorStateClass.MEASUREMENT},
            {"type": "SS", "name": "Solis Grid Time of Use Charge End Minute (Slot 3)", "register": ['43728'],
             "unique": "solis_modbus_inverter_tou_charge_end_minute_3", "multiplier": 0,
             "unit_of_measurement": UnitOfTime.MINUTES, "state_class": SensorStateClass.MEASUREMENT},

            {"type": "SS", "name": "Solis Grid Time of Use Charge cut off SOC (Slot 4)", "register": ['43729'],
             "unique": "solis_modbus_inverter_tou_charge_cutoff_charge_4", "multiplier": 1,
             "unit_of_measurement": PERCENTAGE, "state_class": SensorStateClass.MEASUREMENT, "editable": True, "min": 0,
             "max": 100},
            {"type": "SS", "name": "Solis Grid Time of Use Charge battery current (Slot 4)", "register": ['43730'],
             "unique": "solis_modbus_inverter_tou_charge_v2_battery_current_4", "multiplier": 0.1,
             "device_class": SensorDeviceClass.CURRENT, "unit_of_measurement": UnitOfElectricCurrent.AMPERE,
             "state_class": SensorStateClass.MEASUREMENT, "editable": True, "min": 0, "max": 300},
            {"type": "SS", "name": "Solis Grid Time of Use Charge cut off voltage (Slot 4)", "register": ['43731'],
             "unique": "solis_modbus_inverter_tou_charge_v2_cutoff_voltage_4", "multiplier": 0.1,
             "device_class": SensorDeviceClass.VOLTAGE, "unit_of_measurement": UnitOfElectricPotential.VOLT,
             "state_class": SensorStateClass.MEASUREMENT, "editable": True, "min": 0, "max": 300},

            {"type": "SS", "name": "Solis Grid Time of Use Charge Start Hour (Slot 4)", "register": ['43732'],
             "unique": "solis_modbus_inverter_tou_charge_start_hour_4", "multiplier": 0,
             "unit_of_measurement": UnitOfTime.HOURS, "state_class": SensorStateClass.MEASUREMENT},
            {"type": "SS", "name": "Solis Grid Time of Use Charge Start Minute (Slot 4)", "register": ['43733'],
             "unique": "solis_modbus_inverter_tou_charge_start_minute_4", "multiplier": 0,
             "unit_of_measurement": UnitOfTime.MINUTES, "state_class": SensorStateClass.MEASUREMENT},
            {"type": "SS", "name": "Solis Grid Time of Use Charge End Hour (Slot 4)", "register": ['43734'],
             "unique": "solis_modbus_inverter_tou_charge_end_hour_4", "multiplier": 0,
             "unit_of_measurement": UnitOfTime.HOURS, "state_class": SensorStateClass.MEASUREMENT},
            {"type": "SS", "name": "Solis Grid Time of Use Charge End Minute (Slot 4)", "register": ['43735'],
             "unique": "solis_modbus_inverter_tou_charge_end_minute_4", "multiplier": 0,
             "unit_of_measurement": UnitOfTime.MINUTES, "state_class": SensorStateClass.MEASUREMENT},

            {"type": "SS", "name": "Solis Grid Time of Use Charge cut off SOC (Slot 5)", "register": ['43736'],
             "unique": "solis_modbus_inverter_tou_charge_cutoff_charge_5", "multiplier": 1,
             "unit_of_measurement": PERCENTAGE, "state_class": SensorStateClass.MEASUREMENT, "editable": True, "min": 0,
             "max": 100},
            {"type": "SS", "name": "Solis Grid Time of Use Charge battery current (Slot 5)", "register": ['43737'],
             "unique": "solis_modbus_inverter_tou_charge_v2_battery_current_5", "multiplier": 0.1,
             "device_class": SensorDeviceClass.CURRENT, "unit_of_measurement": UnitOfElectricCurrent.AMPERE,
             "state_class": SensorStateClass.MEASUREMENT, "editable": True, "min": 0, "max": 300},
            {"type": "SS", "name": "Solis Grid Time of Use Charge cut off voltage (Slot 5)", "register": ['43738'],
             "unique": "solis_modbus_inverter_tou_charge_v2_cutoff_voltage_5", "multiplier": 0.1,
             "device_class": SensorDeviceClass.VOLTAGE, "unit_of_measurement": UnitOfElectricPotential.VOLT,
             "state_class": SensorStateClass.MEASUREMENT, "editable": True, "min": 0, "max": 300},

            {"type": "SS", "name": "Solis Grid Time of Use Charge Start Hour (Slot 5)", "register": ['43739'],
             "unique": "solis_modbus_inverter_tou_charge_start_hour_5", "multiplier": 0,
             "unit_of_measurement": UnitOfTime.HOURS, "state_class": SensorStateClass.MEASUREMENT},
            {"type": "SS", "name": "Solis Grid Time of Use Charge Start Minute (Slot 5)", "register": ['43740'],
             "unique": "solis_modbus_inverter_tou_charge_start_minute_5", "multiplier": 0,
             "unit_of_measurement": UnitOfTime.MINUTES, "state_class": SensorStateClass.MEASUREMENT},
            {"type": "SS", "name": "Solis Grid Time of Use Charge End Hour (Slot 5)", "register": ['43741'],
             "unique": "solis_modbus_inverter_tou_charge_end_hour_5", "multiplier": 0,
             "unit_of_measurement": UnitOfTime.HOURS, "state_class": SensorStateClass.MEASUREMENT},
            {"type": "SS", "name": "Solis Grid Time of Use Charge End Minute (Slot 5)", "register": ['43742'],
             "unique": "solis_modbus_inverter_tou_charge_end_minute_5", "multiplier": 0,
             "unit_of_measurement": UnitOfTime.MINUTES, "state_class": SensorStateClass.MEASUREMENT},

            {"type": "SS", "name": "Solis Grid Time of Use Charge cut off SOC (Slot 6)", "register": ['43743'],
             "unique": "solis_modbus_inverter_tou_charge_cutoff_charge_6", "multiplier": 1,
             "unit_of_measurement": PERCENTAGE, "state_class": SensorStateClass.MEASUREMENT, "editable": True, "min": 0,
             "max": 100},
            {"type": "SS", "name": "Solis Grid Time of Use Charge battery current (Slot 6)", "register": ['43744'],
             "unique": "solis_modbus_inverter_tou_charge_v2_battery_current_6", "multiplier": 0.1,
             "device_class": SensorDeviceClass.CURRENT, "unit_of_measurement": UnitOfElectricCurrent.AMPERE,
             "state_class": SensorStateClass.MEASUREMENT, "editable": True, "min": 0, "max": 300},
            {"type": "SS", "name": "Solis Grid Time of Use Charge cut off voltage (Slot 6)", "register": ['43745'],
             "unique": "solis_modbus_inverter_tou_charge_v2_cutoff_voltage_6", "multiplier": 0.1,
             "device_class": SensorDeviceClass.VOLTAGE, "unit_of_measurement": UnitOfElectricPotential.VOLT,
             "state_class": SensorStateClass.MEASUREMENT, "editable": True, "min": 0, "max": 300},
            {"type": "SS", "name": "Solis Grid Time of Use Charge Start Hour (Slot 6)", "register": ['43746'],
             "unique": "solis_modbus_inverter_tou_charge_start_hour_6", "multiplier": 0,
             "unit_of_measurement": UnitOfTime.HOURS, "state_class": SensorStateClass.MEASUREMENT},
            {"type": "SS", "name": "Solis Grid Time of Use Charge Start Minute (Slot 6)", "register": ['43747'],
             "unique": "solis_modbus_inverter_tou_charge_start_minute_6", "multiplier": 0,
             "unit_of_measurement": UnitOfTime.MINUTES, "state_class": SensorStateClass.MEASUREMENT},
            {"type": "SS", "name": "Solis Grid Time of Use Charge End Hour (Slot 6)", "register": ['43748'],
             "unique": "solis_modbus_inverter_tou_charge_end_hour_6", "multiplier": 0,
             "unit_of_measurement": UnitOfTime.HOURS, "state_class": SensorStateClass.MEASUREMENT},
            {"type": "SS", "name": "Solis Grid Time of Use Charge End Minute (Slot 6)", "register": ['43749'],
             "unique": "solis_modbus_inverter_tou_charge_end_minute_6", "multiplier": 0,
             "unit_of_measurement": UnitOfTime.MINUTES, "state_class": SensorStateClass.MEASUREMENT},
        ]
    }, {

        "register_start": 43750,
        "entities": [
            {"type": "SS", "name": "Solis Grid Time of Use Discharge cut off SOC (Slot 1)", "register": ['43750'],
             "unique": "solis_modbus_inverter_tou_charge_cutoff_discharge_1", "multiplier": 1,
             "unit_of_measurement": PERCENTAGE, "state_class": SensorStateClass.MEASUREMENT, "editable": True, "min": 0,
             "max": 100},
            {"type": "SS", "name": "Solis Grid Time of Use Discharge battery current (Slot 1)", "register": ['43751'],
             "unique": "solis_modbus_inverter_tou_discharge_v2_battery_current_1", "multiplier": 0.1,
             "device_class": SensorDeviceClass.CURRENT, "unit_of_measurement": UnitOfElectricCurrent.AMPERE,
             "state_class": SensorStateClass.MEASUREMENT, "editable": True, "min": 0, "max": 300},
            {"type": "SS", "name": "Solis Grid Time of Use Discharge cut off voltage (Slot 1)", "register": ['43752'],
             "unique": "solis_modbus_inverter_tou_discharge_v2_cutoff_voltage_1", "multiplier": 0.1,
             "device_class": SensorDeviceClass.VOLTAGE, "unit_of_measurement": UnitOfElectricPotential.VOLT,
             "state_class": SensorStateClass.MEASUREMENT, "editable": True, "min": 0, "max": 300},

            {"type": "SS", "name": "Solis Grid Time of Use Discharge Start Hour (Slot 1)", "register": ['43753'],
             "unique": "solis_modbus_inverter_tou_discharge_start_hour_1", "multiplier": 0,
             "unit_of_measurement": UnitOfTime.HOURS, "state_class": SensorStateClass.MEASUREMENT},
            {"type": "SS", "name": "Solis Grid Time of Use Discharge Start Minute (Slot 1)", "register": ['43754'],
             "unique": "solis_modbus_inverter_tou_discharge_start_minute_1", "multiplier": 0,
             "unit_of_measurement": UnitOfTime.MINUTES, "state_class": SensorStateClass.MEASUREMENT},
            {"type": "SS", "name": "Solis Grid Time of Use Discharge End Hour (Slot 1)", "register": ['43755'],
             "unique": "solis_modbus_inverter_tou_discharge_end_hour_1", "multiplier": 0,
             "unit_of_measurement": UnitOfTime.HOURS, "state_class": SensorStateClass.MEASUREMENT},
            {"type": "SS", "name": "Solis Grid Time of Use Discharge End Minute (Slot 1)", "register": ['43756'],
             "unique": "solis_modbus_inverter_tou_discharge_end_minute_1", "multiplier": 0,
             "unit_of_measurement": UnitOfTime.MINUTES, "state_class": SensorStateClass.MEASUREMENT},

            {"type": "SS", "name": "Solis Grid Time of Use Discharge cut off SOC (Slot 2)", "register": ['43757'],
             "unique": "solis_modbus_inverter_tou_charge_cutoff_discharge_2", "multiplier": 1,
             "unit_of_measurement": PERCENTAGE, "state_class": SensorStateClass.MEASUREMENT, "editable": True, "min": 0,
             "max": 100},
            {"type": "SS", "name": "Solis Grid Time of Use Discharge battery current (Slot 2)", "register": ['43758'],
             "unique": "solis_modbus_inverter_tou_discharge_v2_battery_current_2", "multiplier": 0.1,
             "device_class": SensorDeviceClass.CURRENT, "unit_of_measurement": UnitOfElectricCurrent.AMPERE,
             "state_class": SensorStateClass.MEASUREMENT, "editable": True, "min": 0, "max": 300},
            {"type": "SS", "name": "Solis Grid Time of Use Discharge cut off voltage (Slot 2)", "register": ['43759'],
             "unique": "solis_modbus_inverter_tou_discharge_v2_cutoff_voltage_2", "multiplier": 0.1,
             "device_class": SensorDeviceClass.VOLTAGE, "unit_of_measurement": UnitOfElectricPotential.VOLT,
             "state_class": SensorStateClass.MEASUREMENT, "editable": True, "min": 0, "max": 300},

            {"type": "SS", "name": "Solis Grid Time of Use Discharge Start Hour (Slot 2)", "register": ['43760'],
             "unique": "solis_modbus_inverter_tou_discharge_start_hour_2", "multiplier": 0,
             "unit_of_measurement": UnitOfTime.HOURS, "state_class": SensorStateClass.MEASUREMENT},
            {"type": "SS", "name": "Solis Grid Time of Use Discharge Start Minute (Slot 2)", "register": ['43761'],
             "unique": "solis_modbus_inverter_tou_discharge_start_minute_2", "multiplier": 0,
             "unit_of_measurement": UnitOfTime.MINUTES, "state_class": SensorStateClass.MEASUREMENT},
            {"type": "SS", "name": "Solis Grid Time of Use Discharge End Hour (Slot 2)", "register": ['43762'],
             "unique": "solis_modbus_inverter_tou_discharge_end_hour_2", "multiplier": 0,
             "unit_of_measurement": UnitOfTime.HOURS, "state_class": SensorStateClass.MEASUREMENT},
            {"type": "SS", "name": "Solis Grid Time of Use Discharge End Minute (Slot 2)", "register": ['43763'],
             "unique": "solis_modbus_inverter_tou_discharge_end_minute_2", "multiplier": 0,
             "unit_of_measurement": UnitOfTime.MINUTES, "state_class": SensorStateClass.MEASUREMENT},

            {"type": "SS", "name": "Solis Grid Time of Use Discharge cut off SOC (Slot 3)", "register": ['43764'],
             "unique": "solis_modbus_inverter_tou_charge_cutoff_discharge_3", "multiplier": 1,
             "unit_of_measurement": PERCENTAGE, "state_class": SensorStateClass.MEASUREMENT, "editable": True, "min": 0,
             "max": 100},
            {"type": "SS", "name": "Solis Grid Time of Use Discharge battery current (Slot 3)", "register": ['43765'],
             "unique": "solis_modbus_inverter_tou_discharge_v2_battery_current_3", "multiplier": 0.1,
             "device_class": SensorDeviceClass.CURRENT, "unit_of_measurement": UnitOfElectricCurrent.AMPERE,
             "state_class": SensorStateClass.MEASUREMENT, "editable": True, "min": 0, "max": 300},
            {"type": "SS", "name": "Solis Grid Time of Use Discharge cut off voltage (Slot 3)", "register": ['43766'],
             "unique": "solis_modbus_inverter_tou_discharge_v2_cutoff_voltage_3", "multiplier": 0.1,
             "device_class": SensorDeviceClass.VOLTAGE, "unit_of_measurement": UnitOfElectricPotential.VOLT,
             "state_class": SensorStateClass.MEASUREMENT, "editable": True, "min": 0, "max": 300},

            {"type": "SS", "name": "Solis Grid Time of Use Discharge Start Hour (Slot 3)", "register": ['43767'],
             "unique": "solis_modbus_inverter_tou_discharge_start_hour_3", "multiplier": 0,
             "unit_of_measurement": UnitOfTime.HOURS, "state_class": SensorStateClass.MEASUREMENT},
            {"type": "SS", "name": "Solis Grid Time of Use Discharge Start Minute (Slot 3)", "register": ['43768'],
             "unique": "solis_modbus_inverter_tou_discharge_start_minute_3", "multiplier": 0,
             "unit_of_measurement": UnitOfTime.MINUTES, "state_class": SensorStateClass.MEASUREMENT},
            {"type": "SS", "name": "Solis Grid Time of Use Discharge End Hour (Slot 3)", "register": ['43769'],
             "unique": "solis_modbus_inverter_tou_discharge_end_hour_3", "multiplier": 0,
             "unit_of_measurement": UnitOfTime.HOURS, "state_class": SensorStateClass.MEASUREMENT},
            {"type": "SS", "name": "Solis Grid Time of Use Discharge End Minute (Slot 3)", "register": ['43770'],
             "unique": "solis_modbus_inverter_tou_discharge_end_minute_3", "multiplier": 0,
             "unit_of_measurement": UnitOfTime.MINUTES, "state_class": SensorStateClass.MEASUREMENT},

            {"type": "SS", "name": "Solis Grid Time of Use Discharge cut off SOC (Slot 4)", "register": ['43771'],
             "unique": "solis_modbus_inverter_tou_charge_cutoff_discharge_4", "multiplier": 1,
             "unit_of_measurement": PERCENTAGE, "state_class": SensorStateClass.MEASUREMENT, "editable": True, "min": 0,
             "max": 100},
            {"type": "SS", "name": "Solis Grid Time of Use Discharge battery current (Slot 4)", "register": ['43772'],
             "unique": "solis_modbus_inverter_tou_discharge_v2_battery_current_4", "multiplier": 0.1,
             "device_class": SensorDeviceClass.CURRENT, "unit_of_measurement": UnitOfElectricCurrent.AMPERE,
             "state_class": SensorStateClass.MEASUREMENT, "editable": True, "min": 0, "max": 300},
            {"type": "SS", "name": "Solis Grid Time of Use Discharge cut off voltage (Slot 4)", "register": ['43773'],
             "unique": "solis_modbus_inverter_tou_discharge_v2_cutoff_voltage_4", "multiplier": 0.1,
             "device_class": SensorDeviceClass.VOLTAGE, "unit_of_measurement": UnitOfElectricPotential.VOLT,
             "state_class": SensorStateClass.MEASUREMENT, "editable": True, "min": 0, "max": 300},

            {"type": "SS", "name": "Solis Grid Time of Use Discharge Start Hour (Slot 4)", "register": ['43774'],
             "unique": "solis_modbus_inverter_tou_discharge_start_hour_4", "multiplier": 0,
             "unit_of_measurement": UnitOfTime.HOURS, "state_class": SensorStateClass.MEASUREMENT},
            {"type": "SS", "name": "Solis Grid Time of Use Discharge Start Minute (Slot 4)", "register": ['43775'],
             "unique": "solis_modbus_inverter_tou_discharge_start_minute_4", "multiplier": 0,
             "unit_of_measurement": UnitOfTime.MINUTES, "state_class": SensorStateClass.MEASUREMENT},
            {"type": "SS", "name": "Solis Grid Time of Use Discharge End Hour (Slot 4)", "register": ['43776'],
             "unique": "solis_modbus_inverter_tou_discharge_end_hour_4", "multiplier": 0,
             "unit_of_measurement": UnitOfTime.HOURS, "state_class": SensorStateClass.MEASUREMENT},
            {"type": "SS", "name": "Solis Grid Time of Use Discharge End Minute (Slot 4)", "register": ['43777'],
             "unique": "solis_modbus_inverter_tou_discharge_end_minute_4", "multiplier": 0,
             "unit_of_measurement": UnitOfTime.MINUTES, "state_class": SensorStateClass.MEASUREMENT},

            {"type": "SS", "name": "Solis Grid Time of Use Discharge cut off SOC (Slot 5)", "register": ['43778'],
             "unique": "solis_modbus_inverter_tou_charge_cutoff_discharge_5", "multiplier": 1,
             "unit_of_measurement": PERCENTAGE, "state_class": SensorStateClass.MEASUREMENT, "editable": True, "min": 0,
             "max": 100},
            {"type": "SS", "name": "Solis Grid Time of Use Discharge battery current (Slot 5)", "register": ['43779'],
             "unique": "solis_modbus_inverter_tou_discharge_v2_battery_current_5", "multiplier": 0.1,
             "device_class": SensorDeviceClass.CURRENT, "unit_of_measurement": UnitOfElectricCurrent.AMPERE,
             "state_class": SensorStateClass.MEASUREMENT, "editable": True, "min": 0, "max": 300},
            {"type": "SS", "name": "Solis Grid Time of Use Discharge cut off voltage (Slot 5)", "register": ['43780'],
             "unique": "solis_modbus_inverter_tou_discharge_v2_cutoff_voltage_5", "multiplier": 0.1,
             "device_class": SensorDeviceClass.VOLTAGE, "unit_of_measurement": UnitOfElectricPotential.VOLT,
             "state_class": SensorStateClass.MEASUREMENT, "editable": True, "min": 0, "max": 300},

            {"type": "SS", "name": "Solis Grid Time of Use Discharge Start Hour (Slot 5)", "register": ['43781'],
             "unique": "solis_modbus_inverter_tou_discharge_start_hour_5", "multiplier": 0,
             "unit_of_measurement": UnitOfTime.HOURS, "state_class": SensorStateClass.MEASUREMENT},
            {"type": "SS", "name": "Solis Grid Time of Use Discharge Start Minute (Slot 5)", "register": ['43782'],
             "unique": "solis_modbus_inverter_tou_discharge_start_minute_5", "multiplier": 0,
             "unit_of_measurement": UnitOfTime.MINUTES, "state_class": SensorStateClass.MEASUREMENT},
            {"type": "SS", "name": "Solis Grid Time of Use Discharge End Hour (Slot 5)", "register": ['43783'],
             "unique": "solis_modbus_inverter_tou_discharge_end_hour_5", "multiplier": 0,
             "unit_of_measurement": UnitOfTime.HOURS, "state_class": SensorStateClass.MEASUREMENT},
            {"type": "SS", "name": "Solis Grid Time of Use Discharge End Minute (Slot 5)", "register": ['43784'],
             "unique": "solis_modbus_inverter_tou_discharge_end_minute_5", "multiplier": 0,
             "unit_of_measurement": UnitOfTime.MINUTES, "state_class": SensorStateClass.MEASUREMENT},

            {"type": "SS", "name": "Solis Grid Time of Use Discharge cut off SOC (Slot 6)", "register": ['43785'],
             "unique": "solis_modbus_inverter_tou_charge_cutoff_discharge_6", "multiplier": 1,
             "unit_of_measurement": PERCENTAGE, "state_class": SensorStateClass.MEASUREMENT, "editable": True, "min": 0,
             "max": 100},
            {"type": "SS", "name": "Solis Grid Time of Use Discharge battery current (Slot 6)", "register": ['43786'],
             "unique": "solis_modbus_inverter_tou_discharge_v2_battery_current_6", "multiplier": 0.1,
             "device_class": SensorDeviceClass.CURRENT, "unit_of_measurement": UnitOfElectricCurrent.AMPERE,
             "state_class": SensorStateClass.MEASUREMENT, "editable": True, "min": 0, "max": 300},
            {"type": "SS", "name": "Solis Grid Time of Use Discharge cut off voltage (Slot 6)", "register": ['43787'],
             "unique": "solis_modbus_inverter_tou_discharge_v2_cutoff_voltage_6", "multiplier": 0.1,
             "device_class": SensorDeviceClass.VOLTAGE, "unit_of_measurement": UnitOfElectricPotential.VOLT,
             "state_class": SensorStateClass.MEASUREMENT, "editable": True, "min": 0, "max": 300},

            {"type": "SS", "name": "Solis Grid Time of Use Discharge Start Hour (Slot 6)", "register": ['43788'],
             "unique": "solis_modbus_inverter_tou_discharge_start_hour_6", "multiplier": 0,
             "unit_of_measurement": UnitOfTime.HOURS, "state_class": SensorStateClass.MEASUREMENT},
            {"type": "SS", "name": "Solis Grid Time of Use Discharge Start Minute (Slot 6)", "register": ['43789'],
             "unique": "solis_modbus_inverter_tou_discharge_start_minute_6", "multiplier": 0,
             "unit_of_measurement": UnitOfTime.MINUTES, "state_class": SensorStateClass.MEASUREMENT},
            {"type": "SS", "name": "Solis Grid Time of Use Discharge End Hour (Slot 6)", "register": ['43790'],
             "unique": "solis_modbus_inverter_tou_discharge_end_hour_6", "multiplier": 0,
             "unit_of_measurement": UnitOfTime.HOURS, "state_class": SensorStateClass.MEASUREMENT},
            {"type": "SS", "name": "Solis Grid Time of Use Discharge End Minute (Slot 6)", "register": ['43791'],
             "unique": "solis_modbus_inverter_tou_discharge_end_minute_6", "multiplier": 0,
             "unit_of_measurement": UnitOfTime.MINUTES, "state_class": SensorStateClass.MEASUREMENT},
        ]
    }, {
        "register_start": 43815,
        "entities": [{"type": "SS", "name": "Solis Generator charging switch",
                      "unique": "solis_modbus_inverter_generator_chargin_switch", "register": ['43815'],
                      "multiplier": 1, "hidden": True,
                      "state_class": SensorStateClass.MEASUREMENT}]
    },
    {
        "register_start": 43340,
        "entities": [{"type": "SS", "name": "Solis Generator Set Enable Switch",
                      "unique": "solis_modbus_inverter_generator_enablement_switch", "register": ['43340'],
                      "multiplier": 1, "hidden": True,
                      "state_class": SensorStateClass.MEASUREMENT}]
    },
    {
        "register_start": 43483,
        "entities": [{"type": "SS", "name": "Solis Hybrid Function Control",
                      "unique": "solis_modbus_inverter_hybrid_function_control", "register": ['43483'], "multiplier": 1,
                      "hidden": True,
                      "state_class": SensorStateClass.MEASUREMENT}]
    },
    {
        "register_start": 43487,
        "entities": [
            {"type": "SS", "name": "Solis Peak Baseline SOC",
             "unique": "solis_modbus_inverter_peak_baseline_soc", "register": ['43487'], "multiplier": 1,
             "device_class": SensorDeviceClass.BATTERY, "unit_of_measurement": PERCENTAGE,
             "state_class": SensorStateClass.MEASUREMENT, "editable": True, "min": 7, "max": 100},
            {"type": "SS", "name": "Solis Peak Max Usable Grid Power",
             "unique": "solis_modbus_inverter_peak_max_usuable_grid_power", "register": ['43488'], "multiplier": 100,
             "device_class": SensorDeviceClass.POWER, "unit_of_measurement": UnitOfPower.WATT,
             "state_class": SensorStateClass.MEASUREMENT, "editable": True, "min": 0, "max": 15000}
        ]
    },
    {
        "register_start": 43249,
        "entities": [{"type": "SS", "name": "Special Settings",
                      "unique": "solis_modbus_inverter_special_settings", "register": ['43249'], "multiplier": 1,
                      "hidden": True,
                      "state_class": SensorStateClass.MEASUREMENT}]
    },
    {
        "register_start": 43110,
        "entities": [{"type": "SS", "name": "Storage control Switch value",
                      "unique": "solis_modbus_inverter_storage_control_switch_value", "register": ['43110'],
                      "multiplier": 1,
                      "hidden": True,
                      "state_class": SensorStateClass.MEASUREMENT}]
    }
]
## Remove 33132 in next update if this works (43110)

hybrid_waveshare_sensors_derived = [
    {"type": "SDS", "name": "Solis Status String",
     "unique": "solis_modbus_inverter_current_status_string", "multiplier": 0,
     "register": ['33095']},

    {"type": "SDS", "name": "Solis PV Power 1",
     "unique": "solis_modbus_inverter_dc_power_1", "device_class": SensorDeviceClass.POWER, "multiplier": 0.1,
     "unit_of_measurement": UnitOfPower.WATT, "state_class": SensorStateClass.MEASUREMENT,
     "register": ['33049', '33050']},

    {"type": "SDS", "name": "Solis PV Power 2",
     "unique": "solis_modbus_inverter_dc_power_2", "device_class": SensorDeviceClass.POWER, "multiplier": 0.1,
     "unit_of_measurement": UnitOfPower.WATT, "state_class": SensorStateClass.MEASUREMENT,
     "register": ['33051', '33052']},

    {"type": "SDS", "name": "Solis PV Power 3",
     "unique": "solis_modbus_inverter_dc_power_3", "device_class": SensorDeviceClass.POWER, "multiplier": 0.1,
     "unit_of_measurement": UnitOfPower.WATT, "state_class": SensorStateClass.MEASUREMENT,
     "register": ['33053', '33054']},

    {"type": "SDS", "name": "Solis PV Power 4",
     "unique": "solis_modbus_inverter_dc_power_4", "device_class": SensorDeviceClass.POWER, "multiplier": 0.1,
     "unit_of_measurement": UnitOfPower.WATT, "state_class": SensorStateClass.MEASUREMENT,
     "register": ['33055', '33056']},

    {"type": "SDS", "name": "Solis Battery Charge Power",
     "unique": "solis_modbus_inverter_battery_charge_power", "device_class": SensorDeviceClass.POWER,
     "multiplier": 0.1,
     "unit_of_measurement": UnitOfPower.WATT, "state_class": SensorStateClass.MEASUREMENT,
     "register": ['33149', '33150', '33135', '0']},
    {"type": "SDS", "name": "Solis Battery Discharge Power",
     "unique": "solis_modbus_inverter_battery_discharge_power", "device_class": SensorDeviceClass.POWER,
     "multiplier": 0.1,
     "unit_of_measurement": UnitOfPower.WATT, "state_class": SensorStateClass.MEASUREMENT,
     "register": ['33149', '33150', '33135', '1']}
]
