name: Mark stale issues and PRs

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight UTC

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: "This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs."
          stale-pr-message: "This PR has been automatically marked as stale due to inactivity. It will be closed if no further updates are made."
          close-issue-message: "Closing this issue due to inactivity. Feel free to reopen if needed."
          close-pr-message: "Closing this PR due to inactivity."
          days-before-stale: 14 # Number of days before marking as stale
          days-before-close: 7 # Number of days before closing after being marked stale
          exempt-issue-labels: "pinned,security" # Issues with these labels won't be marked stale
          exempt-pr-labels: "pinned,security"
          remove-stale-when-updated: true
